### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by greenscientist** [chairemobilite/trRouting#32]
Core was generated by `./trRoutingCSA --project=demo_transition --port=4000 --osrmPort=5000'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005583f453a445 in std::__uniq_ptr_impl<TrRouting::Node, std::default_delete<TrRouting::Node> >::_M_ptr (this=<optimized out>, this=<optimized out>) at /usr/include/c++/8/bits/unique_ptr.h:342
342	      get() const noexcept
[Current thread is 1 (Thread 0x7fc895460700 (LWP 55966))]
(gdb) bt
#0  0x00005583f453a445 in std::__uniq_ptr_impl<TrRouting::Node, std::default_delete<TrRouting::Node> >::_M_ptr (this=<optimized out>, this=<optimized out>) at /usr/include/c++/8/bits/unique_ptr.h:342
#1  std::unique_ptr<TrRouting::Node, std::default_delete<TrRouting::Node> >::get (this=<optimized out>, this=<optimized out>) at /usr/include/c++/8/bits/unique_ptr.h:343
#2  TrRouting::Calculator::forwardCalculation (this=0x7ffecbc36920) at forward_calculation.cpp:135
#3  TrRouting::Calculator::calculate (this=<optimized out>, resetAccessPaths=<optimized out>, resetFilters=<optimized out>) at calculator.cpp:32
#4  0x00005583f454737a in main::{lambda(std::shared_ptr<SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::Response>, std::shared_ptr<SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::Request>)#4}::operator()(std::shared_ptr<SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::Response>, std::shared_ptr<SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::Request>) const [clone .isra.1320] [clone .lto_priv.1474] ()
    at transit_routing_http_server.cpp:363
#5  0x00005583f45614f5 in std::_M_invoke (__functor=..., __args#0=..., __args#1=...) at /usr/include/c++/8/bits/shared_ptr_base.h:754
#6  0x00005583f4567384 in std::function<void (std::shared_ptr<SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::Response>, std::shared_ptr<SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::Request>)>::operator()(std::shared_ptr<SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::Response>, std::shared_ptr<SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::Request>) const (
    __args#1=std::shared_ptr<SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::Request> (empty) = {...}, 
    __args#0=std::shared_ptr<SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::Response> (use count 1575486836, weak count 1207962494) = {...}, this=0x5584526139c0) at /usr/include/c++/8/bits/std_function.h:682
#7  SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::write(std::shared_ptr<SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::Session> const&, std::function<void (std::shared_ptr<SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::Response>, std::shared_ptr<SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::Request>)>&) (this=<optimized out>, session=..., resource_function=...) at ../../include/server_http.hpp:777
#8  0x00005583f456cfb2 in SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::find_resource (this=<optimized out>, session=..., this=<optimized out>, session=...) at /usr/include/c++/8/bits/allocator.h:139
#9  0x00005583f4565dc1 in boost::asio::detail::read_until_delim_string_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::basic_streambuf_ref<std::allocator<char> >, SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::read(std::shared_ptr<SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::Session> const&)::{lambda(boost::system::error_code const&, unsigned long)#1}>::operator()(boost::system::error_code const&, unsigned long, int) (this=<optimized out>, ec=..., 
    bytes_transferred=<optimized out>, start=<optimized out>) at /usr/include/c++/8/ext/new_allocator.h:86
#10 0x00005583f45594da in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::detail::read_until_delim_string_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::basic_streambuf_ref<std::allocator<char> >, SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::read(std::shared_ptr<SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::Session> const&)::{lambda(boost::system::error_code const&, unsigned long)#1}> >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) (owner=<optimized out>, base=<optimized out>) at /usr/include/boost/asio/detail/bind_handler.hpp:162
#11 0x00005583f454cfa0 in boost::asio::detail::scheduler_operation::complete (bytes_transferred=0, ec=..., owner=0x7fc880000ba0, this=<optimized out>) at /usr/include/boost/asio/detail/scheduler_operation.hpp:40
#12 boost::asio::detail::scheduler::do_run_one (ec=..., this_thread=..., lock=..., this=<optimized out>) at /usr/include/boost/asio/detail/impl/scheduler.ipp:401
#13 boost::asio::detail::scheduler::run (ec=..., this=0x7fc880000ba0) at /usr/include/boost/asio/detail/impl/scheduler.ipp:154
#14 boost::asio::io_context::run() [clone .isra.488] [clone .lto_priv.1367] (this=<optimized out>) at /usr/include/boost/asio/impl/io_context.ipp:62
#15 0x00005583f452ff50 in SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::start(std::function<void (unsigned short)> const&) [clone .constprop.59] (this=0x7ffecbc35fd0, callback=...) at ../../include/server_http.hpp:463
#16 0x00005583f454b4be in <lambda()>::operator() (__closure=<optimized out>) at /usr/include/c++/8/bits/std_function.h:402
#17 std::__invoke_impl<void, main(int, char**)::<lambda()> > (__f=...) at /usr/include/c++/8/bits/invoke.h:60
#18 std::__invoke<main(int, char**)::<lambda()> > (__fn=...) at /usr/include/c++/8/bits/invoke.h:95
#19 std::thread::_Invoker<std::tuple<main(int, char**)::<lambda()> > >::_M_invoke<0> (this=<optimized out>) at /usr/include/c++/8/thread:244
#20 std::thread::_Invoker<std::tuple<main(int, char**)::<lambda()> > >::operator() (this=<optimized out>) at /usr/include/c++/8/thread:253
#21 std::_M_run (this=<optimized out>) at /usr/include/c++/8/thread:196
#22 0x00007fc897961b2f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#23 0x00007fc897caffa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#24 0x00007fc8976414cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by greenscientist** [comment]
Duplicate  of #26
